### ISSUE TITLE
README

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld#1]
il file README serve per la descrizione del progetto, non per il codice

**Comment by FabioZTessitore** [comment]
Il file README, invece, va ripulito

**Comment by tonyiovino** [comment]
Va bene

Il giorno Mar 23 Apr 2019 14:12 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
una cosa alla volta, aggiustiamo prima il README perché vedo che sei riuscito a ripulirlo

Apri il README e scrivici dentro il nome della repository preceduto da #

```
# helloworld
```

Salva e fai add, commit e push

**Comment by tonyiovino** [comment]
Devo cliccare su "Commit changes"?

Il giorno Mar 23 Apr 2019 14:18 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
no. non ci stiamo capendo. NON devi usare github per fare le modifiche ai file.

Se sul tuo pc hai la directory hello world, cancellala
Fai il clone della repository
Modifica i file sul tuo pc
add, commit e push da terminale

**Comment by tonyiovino** [comment]
Ah okay

Il giorno Mar 23 Apr 2019 14:25 Fabio Z Tessitore <notifications@github.com>
ha scritto:
