### ISSUE TITLE
Secondogrado.py

### ISSUE THREAD

**Issue by tonyiovino** [tonyiovino/helloworld#10]

**Comment by tonyiovino** [comment]
Come posso avere la radice quadrata?
Import math? e poi?

**Comment by FabioZTessitore** [comment]
`math.sqrt(...)`

**Comment by tonyiovino** [comment]
Scusate, ma il cursore che ci fa capire dove saranno messi i caratteri da me digitati, è nero. Non per razzismo (HAHAHAHA), ma voglio quello bianco, poichè quando vado sopra al testo mi sostituisce i caratteri.

**Comment by FabioZTessitore** [comment]
hai premuto INS per errore, ripremilo

**Comment by tonyiovino** [comment]
Thanks!

**Comment by tonyiovino** [comment]
Dov'è l'errore ora? :(

**Comment by tonyiovino** [comment]
Credo nel "sqrt(.....)"

**Comment by FabioZTessitore** [comment]
math.sqrt

**Comment by tonyiovino** [comment]
E ora, invece?

**Comment by FabioZTessitore** [comment]
che errore ti dà?

**Comment by tonyiovino** [comment]
math domain error

**Comment by FabioZTessitore** [comment]
è quel problema di cui ti ho accennato. Se il valore sotto radice è negativo non si può fare la radice

**Comment by tonyiovino** [comment]
Ah

**Comment by tonyiovino** [comment]
Okay... In pratica, non c'è nessun errore ora...
C'è solo un piccolissimo problema, che dopo aver messo i valori non appare nulla. 
Esempio:
$ ....A: 5
$ ....B: 5
$ ....C: 5
$

**Comment by FabioZTessitore** [comment]
perché non stampi i risultati?

**Comment by tonyiovino** [comment]
Che sbadato...
Sarà stata la fame, HAHAHA

**Comment by tonyiovino** [comment]
Ecoo, fatto.

**Comment by FabioZTessitore** [comment]
ma dove l'hai messa quella print???

**Comment by tonyiovino** [comment]
??

**Comment by tonyiovino** [comment]
Sembra tutto giusto...

**Comment by tonyiovino** [comment]
Funziona anche...

**Comment by FabioZTessitore** [comment]
ora hai corretto la posizione della print.

Cmq, un paio di correzioni:

1. le X da calcolare sono due
2. I calcoli non sono corretti perché mancano delle parentesi (anche se le equazioni di secondo grado non le hai studiate, devi essere capace di copiare una formula una volta che ti è stata data)

**Comment by tonyiovino** [comment]
Sì, avete ragione. 😕

Il giorno Mar 7 Mag 2019 08:24 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Ora mi metto a lavoro.

**Comment by tonyiovino** [comment]
Non lo so fare, aiutatemi... :(

**Comment by tonyiovino** [comment]
Guardate:
Non so come mettere X1 o X2.

**Comment by FabioZTessitore** [comment]
Sono normali nomi di variabili

Il mar 7 mag 2019, 20:18 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Vi lascio l'ultima modifica, vado un attimo a mangiare.

**Comment by tonyiovino** [comment]
Rieccomi, non ho capito precisamente dove sbaglio, e se lo so, non saprei come aggiustare.

**Comment by FabioZTessitore** [comment]
non c'entra niente l'or. Devi stampare sia x1 che x2

**Comment by tonyiovino** [comment]
Ah...

Il giorno mer 8 mag 2019 alle ore 18:03 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Il tempo che finisco alcune cose per il lavoro e mi metto all'opera.

Il giorno mer 8 mag 2019 alle ore 18:04 Tjony Official <
antonioiovino2004tony@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
per completare l'esercizio devi aggiustare le parentesi delle formule

**Comment by tonyiovino** [comment]
lasciando lo spazio?

**Comment by FabioZTessitore** [comment]
non è un problema di spazi, ma di parentesi. Il numeratore (tutto) diviso il denominatore (tutto)

**Comment by tonyiovino** [comment]
Ora?

**Comment by FabioZTessitore** [comment]
non ancora

**Comment by tonyiovino** [comment]
Ora mi sono accorto dov'è l'errore. Ma non so se ho corretto nel modo corretto.

**Comment by tonyiovino** [comment]
Ho corretto nel modo giusto le parentesi.
