### ISSUE TITLE
hello.py

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld#2]
Bisogna creare un file con il codice (e devi imparare a mandarlo in esecuzione)

**Comment by tonyiovino** [comment]
> 

>

**Comment by FabioZTessitore** [comment]
Il file hello.py deve essere creato nella tua cartella di lavoro e poi pushato su github

**Comment by tonyiovino** [comment]
Tramite terminale?

Il giorno Mar 23 Apr 2019 14:11 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
la solita procedura, crei il file, lo salvi, e fai i tre passi (add, commit, push)

**Comment by tonyiovino** [comment]
Perdonatemi, non sto capendo :-(

**Comment by FabioZTessitore** [comment]
Ora cerchiamo di fare questo.
Nella tua cartella locale devi creare il file hello.py
e poi fare i tre passi soliti (add, commit e push)

**Comment by tonyiovino** [comment]
Il giorno Mar 23 Apr 2019 18:22 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
problemi?

**Comment by tonyiovino** [comment]
Ho creato il file hello.py nella directory di nome "helloworld"

Il giorno Mar 23 Apr 2019 18:43 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
ok, ora devi fare i tre passi (add, commit e push)

**Comment by tonyiovino** [comment]
add commit e push? 😐

Il giorno Mar 23 Apr 2019 18:45 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
```
$ git add hello.py
$ git commit -m "hello"
$ git push origin master
```

Ricordati di fare 
```
$ git config ...
```
prima

**Comment by tonyiovino** [comment]
Aaaah okaaay

Il giorno Mar 23 Apr 2019 18:48 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
???

Il giorno Mar 23 Apr 2019 18:48 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
che c'è?

**Comment by tonyiovino** [comment]
Esce scritto "fatal: not a git repository  (or any of the parent
directories): .git

Il giorno Mar 23 Apr 2019 19:00 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
non sei nella cartella giusta. Apri il terminale nella cartella dove c'è il progetto o usa cd

**Comment by tonyiovino** [comment]
Ho fatto, ma esce sempre la stessa cosa.

Il giorno Mar 23 Apr 2019 19:04 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
la cartella in cui stai lavorando è quella che hai clonato?

**Comment by tonyiovino** [comment]
Allora, ho fatto git config...
Ho cliccato su "clone or download" e ho cliccato sulla icona che mi fa
copiare l' URL.
Ora?

Il giorno Mar 23 Apr 2019 19:09 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
```
git clone url_che_hai_copiato
```

**Comment by tonyiovino** [comment]
"fatal: il patho di destinazione 'helloworld ' esiste già e non è una
directory vuota."

Il giorno Mar 23 Apr 2019 19:22 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
cancella la directory helloworld e rifai il clone

**Comment by tonyiovino** [comment]
Fattoo

Il giorno Mar 23 Apr 2019 19:27 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
ora entra in questa cartella, aggiungi il file hello.py e fai i tre passi che ti ho scritto prima

**Comment by tonyiovino** [comment]
Fatto

Il giorno Mar 23 Apr 2019 19:31 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
ci siamo quasi.
nel file hello.py ci devi scrivere il codice!!!

**Comment by tonyiovino** [comment]
Come? 😅😅

Il giorno Mar 23 Apr 2019 19:36 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
è un semplice file di testo

**Comment by tonyiovino** [comment]
Sì, sempre tramite terminale?

Il giorno Mar 23 Apr 2019 19:41 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
sempre

**Comment by FabioZTessitore** [comment]
no, scherzo.
tasto destro, per ora puoi usare mousepad

**Comment by tonyiovino** [comment]
Aah okay

Il giorno Mar 23 Apr 2019 19:46 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Fatto, ora?

Il giorno Mar 23 Apr 2019 19:49 Tjony Official <
antonioiovino2004tony@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
non mi sembra

**Comment by tonyiovino** [comment]
Ho solo scritto il codice, ho ancora aperto mousepad

Il giorno Mar 23 Apr 2019 20:11 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
quando finisci di scrivere devi fare i tre passaggi (add, commit e push)

**Comment by tonyiovino** [comment]
Tramite terminale o mousepad?

Il giorno Mar 23 Apr 2019 21:17 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
i tre passaggi sono tramite terminale

**Comment by tonyiovino** [comment]
Devo salvare e uscire dal mousepad?

Il giorno Mar 23 Apr 2019 21:35 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
certo

**Comment by tonyiovino** [comment]
Quando faccio add dice che non esiste una reposity "hello.py"

Il giorno Mar 23 Apr 2019 21:37 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
devi stare nella cartella

**Comment by tonyiovino** [comment]
Fatto

Il giorno Mar 23 Apr 2019 21:40 Fabio Z Tessitore <notifications@github.com>
ha scritto:
