### ISSUE TITLE
correzioni

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld#4]
`Come ti chiami` è una stringa, ci vogliono le virgolette singole o doppie

```
name =input(Come ti chiami?)
```

Qui, invece, `name` è la variabile che contiene il nome dell'utente. **Non** deve stare tra virgolette

```
print("Hello, name")
```

**Comment by tonyiovino** [comment]
Okay, riprovo?

**Comment by FabioZTessitore** [comment]
ovviamente

**Comment by tonyiovino** [comment]
Okay!

Il giorno Mar 23 Apr 2019 22:05 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
FATTO!!! :-)

**Comment by FabioZTessitore** [comment]
hai provato a mandarlo in esecuzione?

**Comment by tonyiovino** [comment]
Nope :-(
Come si fa'?

**Comment by FabioZTessitore** [comment]
da terminale
```
python hello.py
```

**Comment by tonyiovino** [comment]
Con quale comando?

**Comment by tonyiovino** [comment]
aah okay

**Comment by tonyiovino** [comment]
SIII HA FUNZIONATO!

**Comment by FabioZTessitore** [comment]
ok
