### ISSUE TITLE
sfera.py HELP!

### ISSUE THREAD

**Issue by tonyiovino** [tonyiovino/helloworld#5]
non so come si faccia...

**Comment by FabioZTessitore** [comment]
Comincia a fare una ricerca. Come si calcola il volume di una sfera?

Il ven 26 apr 2019, 12:50 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
V = 4/3 "pi greco" * r elevato alla potenza di 3

**Comment by FabioZTessitore** [comment]
Ok. r devi chiederlo all'utente (e deve essere intero). La formula ti
permette di calcolare il volume

Il ven 26 apr 2019, 12:55 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ci provo...

**Comment by tonyiovino** [comment]
E il pi greco?
Dopo aver fatto "import math" e "math.pi", come lo devo scrivere il pi greco?

**Comment by FabioZTessitore** [comment]
math.pi è una variabile predefinita che vale 3.14 ecc ecc. È lei pi greco

Il ven 26 apr 2019, 13:02 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
quindi devo scrivere direttamente math.pi ?

**Comment by FabioZTessitore** [comment]
Si, dove serve

Il ven 26 apr 2019, 13:07 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
okay!

**Comment by FabioZTessitore** [comment]
che ti sei inventato qui?

```
r = int
```

**Comment by tonyiovino** [comment]
Ho dimenticato le parentesi 😂

Il giorno Ven 26 Apr 2019 16:40 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Il giorno Dom 28 Apr 2019 23:32 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Il giorno Lun 29 Apr 2019 00:14 Tjony Official <
antonioiovino2004tony@gmail.com> ha scritto:
