### ISSUE TITLE
paridisp

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld#6]
I programmi devi mandarli in esecuzione ... ti renderesti conto che non funzionano

**Comment by tonyiovino** [comment]
Si, lo so che non funzionano, per questo ve l'ho mandato, perché voglio sapere l'errore dov'è.

**Comment by FabioZTessitore** [comment]
Devi rivedere l'if in python

Il mer 1 mag 2019, 19:04 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
L'ho fatto :-(

**Comment by FabioZTessitore** [comment]
cosa hai fatto esattamente?

**Comment by tonyiovino** [comment]
Proprio ora mi stavo mettendo a lavoro, perché ho notato che c'è dello
spazio nel esempio di if e else, ma non ho capito quantonia spazio debba
lasciare.

Il giorno Gio 2 Mag 2019 18:54 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Quanto*

Il giorno Gio 2 Mag 2019 18:56 Tjony Official <
antonioiovino2004tony@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
decidi tu, l'importante è usare sempre la stessa quantità.
Una scelta classica è 4 spazi

**Comment by tonyiovino** [comment]
Okay!

Il giorno Gio 2 Mag 2019 18:59 Fabio Z Tessitore <notifications@github.com>
ha scritto:
