### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld#7]
ma funziona?

**Comment by tonyiovino** [comment]
Nope :-(

**Comment by FabioZTessitore** [comment]
appunto. Non facciamo che andiamo avanti e dimentichiamo le cose "vecchie".

probabilmente non fa né il caso 1 né il 2, quindi dove sarà l'errore?

**Comment by tonyiovino** [comment]
if, else, e elif?

**Comment by FabioZTessitore** [comment]
più o meno

se nessuna delle alternative va, chi è responsabile?

**Comment by tonyiovino** [comment]
Ah forse ho capito...

**Comment by tonyiovino** [comment]
Ho corretto dove non ho messo " scelta = int(scelta) "

**Comment by tonyiovino** [comment]
Ma comunque non funziona.
Penso sia per if, else, e elif menzionati prima.

**Comment by FabioZTessitore** [comment]
Non vedo questa modifica:

Ho corretto dove non ho messo " scelta = int(scelta) "

**Comment by tonyiovino** [comment]
ancora devo fare i famosi add commit e push

**Comment by tonyiovino** [comment]
Ora si.

**Comment by FabioZTessitore** [comment]
ci siamo quasi.
Ora controlla l'else. Qual è la differenza tra else e else if?

**Comment by tonyiovino** [comment]
Ah...
Mi sarò confuso...

**Comment by tonyiovino** [comment]
Corretto!
