### ISSUE TITLE
primo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld#9]
il programma non dà soluzioni corrette

**Comment by tonyiovino** [comment]
Prof! Buonasera! Dopo un estenuante pomeriggio direi che posso mettermi a lavoro con "secondogrado.py"

**Comment by tonyiovino** [comment]
Ma prima, devo correggere "primogrado.py".

**Comment by FabioZTessitore** [comment]
Attendo

**Comment by tonyiovino** [comment]
Ecco che arriva "primogrado.py".
